In [1]:
teens <- read.csv("../csv/snsdata.csv")

In [2]:
str(teens)

'data.frame':	30000 obs. of  40 variables:
 $ gradyear    : int  2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 ...
 $ gender      : Factor w/ 2 levels "F","M": 2 1 2 1 NA 1 1 2 1 1 ...
 $ age         : num  19 18.8 18.3 18.9 19 ...
 $ friends     : int  7 0 69 0 10 142 72 17 52 39 ...
 $ basketball  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ football    : int  0 1 1 0 0 0 0 0 0 0 ...
 $ soccer      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ softball    : int  0 0 0 0 0 0 0 1 0 0 ...
 $ volleyball  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ swimming    : int  0 0 0 0 0 0 0 0 0 0 ...
 $ cheerleading: int  0 0 0 0 0 0 0 0 0 0 ...
 $ baseball    : int  0 0 0 0 0 0 0 0 0 0 ...
 $ tennis      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ sports      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ cute        : int  0 1 0 1 0 0 0 0 0 1 ...
 $ sex         : int  0 0 0 0 1 1 0 2 0 0 ...
 $ sexy        : int  0 0 0 0 0 0 0 1 0 0 ...
 $ hot         : int  0 0 0 0 0 0 0 0 0 1 ...
 $ kissed      : int  0 0 0 0 5 0 0 0 0 0 ...
 $ dance       : int  1 0 0 0 1 0 0 0 0 0 ...
 $ band        : int  0 0 2 0 1 0 1 0 0 0 ...
 $ marching    : int  0 0 0 0 0 1 1 0 0 0 ...
 $ music       : int  0 2 1 0 3 2 0 1 0 1 ...
 $ rock        : int  0 2 0 1 0 0 0 1 0 1 ...
 $ god         : int  0 1 0 0 1 0 0 0 0 6 ...
 $ church      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ jesus       : int  0 0 0 0 0 0 0 0 0 2 ...
 $ bible       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ hair        : int  0 6 0 0 1 0 0 0 0 1 ...
 $ dress       : int  0 4 0 0 0 1 0 0 0 0 ...
 $ blonde      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ mall        : int  0 1 0 0 0 0 2 0 0 0 ...
 $ shopping    : int  0 0 0 0 2 1 0 0 0 1 ...
 $ clothes     : int  0 0 0 0 0 0 0 0 0 0 ...
 $ hollister   : int  0 0 0 0 0 0 2 0 0 0 ...
 $ abercrombie : int  0 0 0 0 0 0 0 0 0 0 ...
 $ die         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ death       : int  0 0 1 0 0 0 0 0 0 0 ...
 $ drunk       : int  0 0 0 0 1 1 0 0 0 0 ...
 $ drugs       : int  0 0 0 0 1 0 0 0 0 0 ...

In [3]:
table(teens$gender, useNA = "ifany")
summary(teens$age)

    F     M  <NA>
22054  5222  2724

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
  3.086  16.310  17.290  17.990  18.260 106.900    5086

In [6]:
teens$age <- ifelse(teens$age >= 13 & teens$age < 20, teens$age, NA)

In [7]:
summary(teens$age)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
  13.03   16.30   17.26   17.25   18.22   20.00    5523

In [8]:
teens$female <- ifelse(teens$gender == "F" & !is.na(teens$gender), 1, 0)
teens$no_gender <- ifelse(is.na(teens$gender), 1, 0)

In [9]:
table(teens$gender, useNA = "ifany")
table(teens$female, useNA = "ifany")
table(teens$no_gender, useNA = "ifany")

    F     M  <NA>
22054  5222  2724

    0     1
 7946 22054

    0     1
27276  2724

In [10]:
mean(teens$age, na.rm = TRUE)

[1] 17.25243

In [11]:
aggregate(data = teens, age ~ gradyear, mean, na.rm = TRUE)

  gradyear      age
1     2006 18.65586
2     2007 17.70617
3     2008 16.76770
4     2009 15.81957

In [13]:
ave_age <- ave(teens$age, teens$gradyear, FUN = function(x) mean(x, na.rm=TRUE))

In [15]:
teens$age <- ifelse(is.na(teens$age), ave_age, teens$age) 
summary(teens$age)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  13.03   16.28   17.24   17.24   18.21   20.00

In [16]:
library(stats)

In [17]:
interests <- teens[5:40]

In [18]:
interests_z <- as.data.frame(lapply(interests, scale))

In [20]:
teens_clusters <- kmeans(interests_z, 5)

In [21]:
teens_clusters$size

[1]   607   598  1073 22381  5341

In [22]:
teens_clusters$centers

   basketball    football      soccer    softball  volleyball    swimming
1  0.10385481  0.03936434  0.02475166  0.02260925  0.02089888  0.08100109
2 -0.08699919  0.06430628 -0.09884115 -0.02124497 -0.06949237  0.04408330
3  0.37078097  0.38089845  0.14526906  0.16508947  0.11274592  0.26821817
4 -0.14265209 -0.14491583 -0.07334905 -0.10158737 -0.10448325 -0.09195650
5  0.52121963  0.51906157  0.28643215  0.39233599  0.42058307  0.31730965
  cheerleading    baseball      tennis       sports        cute          sex
1  -0.02154527  0.03885679  0.06051293  0.003637869 -0.03280777 -0.014818612
2  -0.10978518 -0.11138143  0.04132290 -0.101879475 -0.02307813 -0.039028055
3   0.21305835  0.27403221  0.11770589  0.850330191  0.47915767  2.025943203
4  -0.11280766 -0.09227849 -0.03764940 -0.109984488 -0.17935300 -0.095031562
5   0.44464822  0.33968702  0.12261569  0.301043676  0.66161361 -0.002733945
         sexy         hot      kissed        dance        band    marching
1 -0.08330154 -0.01666271 -0.04736064 -0.008610341  0.08119947 -0.03812720
2 -0.02671232 -0.03736727 -0.03845769  0.057176686  4.09671211  5.21738142
3  0.50548380  0.32707791  2.96652960  0.456771698  0.37613105 -0.01806145
4 -0.08638215 -0.13264342 -0.13357782 -0.148182898 -0.11830677 -0.11138158
5  0.27288386  0.49619877 -0.02653724  0.523759638 -0.04772265 -0.10946259
       music        rock         god      church        jesus       bible
1  0.1948669  0.08986874  2.47451053  1.90489482  2.565794048  4.59710682
2  0.5071012  0.17290955  0.06567153  0.05132108  0.011453196 -0.04704558
3  1.2005642  1.21597626  0.34950362  0.13601016  0.063688112  0.03237634
4 -0.1298448 -0.10928957 -0.10191617 -0.12231709 -0.070830894 -0.10424551
5  0.2239882  0.18410731  0.06827726  0.26299921 -0.008866711 -0.08686231
         hair       dress       blonde        mall     shopping      clothes
1  0.03676443  0.01702016  0.003348183 -0.11891692  0.003932181  0.020427515
2 -0.04370362  0.07308273 -0.012192895 -0.07187677 -0.030227227  0.007773175
3  2.59024182  0.55559433  0.362190576  0.64677111  0.294917665  1.304681174
4 -0.19934021 -0.12680839 -0.028115882 -0.18187574 -0.219982963 -0.179670133
5  0.31565671  0.40964447  0.046038210  0.65376154  0.865508537  0.487591555
    hollister abercrombie         die       death        drunk       drugs
1 -0.09220673 -0.07105991  0.20906155  0.25519217  0.072664091  0.03488729
2 -0.17253970 -0.14713798  0.00243185  0.06006217 -0.090516081 -0.06359023
3  0.37902501  0.46371777  1.67206579  0.94184946  1.764373022  2.66532551
4 -0.15444453 -0.14882552 -0.09088614 -0.07259225 -0.085055208 -0.11102359
5  0.60083832  0.55503029  0.02090273  0.07924804  0.003832593 -0.06707076

In [24]:
teens$cluster <- teens_clusters$cluster

In [25]:
teens[1:5, c("cluster", "gender", "age", "friends")]

  cluster gender    age friends
1       4      M 18.982       7
2       5      F 18.801       0
3       4      M 18.335      69
4       4      F 18.875       0
5       3   <NA> 18.995      10

In [27]:
aggregate(data = teens, female ~ cluster, mean)

  cluster    female
1       1 0.7479407
2       2 0.7257525
3       3 0.8089469
4       4 0.7018453
5       5 0.8593896

In [28]:
aggregate(data = teens, friends ~ cluster, mean)

  cluster  friends
1       1 34.90610
2       2 32.62375
3       3 30.49953
4       4 27.88231
5       5 38.93035